const connectDB = require('../models/mongoose')
const { createRandomEntities } = require('./SeedUtils')
const seedUsers = require('./User')
const seedPosts = require('./Post')
const seedCommunities = require('./Community')
const seedComments = require('./Comment')
const seedNotifications = require('./Notification')
const seedHistory = require('./History')
const seedChatRooms = require('./ChatRoom')
const seedMessages = require('./Message')
const seedChatRequests = require('./ChatRequest')
const seedReports = require('./Report')
const seedChatMessages = require('./ChatMessage')

connectDB()

async function seed () {
  createRandomEntities()
  await seedUsers()
  await seedCommunities()
  await seedPosts()
  await seedComments()
  await seedNotifications()
  await seedHistory()
  await seedChatRooms()
  await seedChatRequests()
  await seedMessages()
  await seedReports()
  await seedChatMessages()
  process.exit()
}

seed()
