const USERS = 100
const POSTS = 10000
const COMMENTS = 10000
const COMMUNITIES = 10
const HISTORY = 500
const NOTIFICATIONS = 1000
const CHAT_ROOMS = 50
const MESSAGES = 200

module.exports = {
  USERS,
  POSTS,
  COMMENTS,
  COMMUNITIES,
  HISTORY,
  NOTIFICATIONS,
  CHAT_ROOMS,
  MESSAGES
}
